# -*- coding: utf-8 -*-
"""Pandas Dataframe.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAfDcazj3Ta6bm6lYE51ZBRf1ZYUs0pD
"""

# Q1 :- Create a Pandas DataFrame using a Python dictionary with specific columns and at least 5 rows of sample data.

import pandas as pd

# Creating the dictionary with required columns
data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Webcam'],
    'Region': ['North', 'South', 'East', 'West', 'North'],
    'Sales': [1200, 25, 300, 75, 110],
    'Quantity': [1, 5, 2, 3, 2]
}

# Converting dictionary to DataFrame
df_sample = pd.DataFrame(data)

# Displaying the DataFrame
print(df_sample)

#Q2 :- Data Inspection

#Load the dataset
df=pd.read_csv("Retail_dataset.csv")

# 1. Display first 5 rows
df.head()

# 2. Display last 5 rws
df.tail()

# 3 :- Show structure using info()
df.info()

# 4. Display shape
print("Dataset Shape:", df.shape)

#Q3 :-Select and display only specific columns.

df[['Product', 'Region', 'Sales']]

#Q4 :- Access specific rows and values using label-based indexing.

# 1. Display the row with index 10
df.loc[10]

# 2. Display Sales value of the row with index 20
df.loc[20, 'Sales']

#Q5 :- Access data using integer-based indexing.

# 1. First 6 rows and first 4 columns
df.iloc[:6, :4]

# 2. Sales value from the 3rd row
df.iloc[2, 2]

#Q6 :- Display specific ranges of rows.
# 1. First 10 rows
df.iloc[:10]

# 2. Rows 15 to 25 [cite: 53]
df.iloc[15:26]

#Q7 :- Filter data based on specific criteria.
# 1. Rows where Region = "East"
df[df['Region'] == 'East']

# 2. Rows where Sales > 1500
df[df['Sales'] > 1500]

#Q8 :- Filter using multiple logical conditions.
# Region is West AND Sales > 1200
df[(df['Region'] == 'West') & (df['Sales'] > 1200)]

#Q9 :- Identify key values from the summary statistics.
# Generate summary statistics [cite: 63]
df.describe()

# Identify specific values
print("Mean Sales:", df['Sales'].mean())
print("Max Quantity:", df['Quantity'].max())
print("Min Sales:", df['Sales'].min())

#Q10 :- Calculate specific aggregate values for the Sales column.
# Calculating requested metrics
print("Total Sales:", df['Sales'].sum())
print("Average Sales:", df['Sales'].mean())
print("Maximum Sales:", df['Sales'].max())
print("Minimum Sales:", df['Sales'].min())